# Generated by Django 4.2 on 2023-06-21 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='customer_nees',
            new_name='customer_need',
        ),
    ]
